### ISSUE TITLE
Middle clicking a tab title should kill the tab

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#117]
This is a common UX across most tabbed applications.

**Comment by iamstarkov** [comment]
which one for example?

**Comment by iamstarkov** [comment]
neither standard terminal, nor iTerm and none of the browsers have this feature implemented

**Comment by Tyriar** [comment]
Firefox, Chrome, Edge, VS Code, Visual Studio, Atom.

**Comment by iamstarkov** [comment]
oh, you mean not click in the middle of tab, but click with scroll-wheel

**Comment by mauriciosoares** [comment]
I believe this issue was closed with this merged PR right? https://github.com/zeit/hyper/pull/286

**Comment by Tyriar** [comment]
Yes this is fixed

**Comment by chazt3n** [comment]
it doesn't work now

**Comment by xoorath** [comment]
@Tyriar As Chazt3n mentioned, this isn't working.

I'm on 3.0.2 canary and can't middle click a tab to close it.

**Comment by LabhanshAgrawal** [comment]
@xoorath it's fixed on canary, you can get it from https://github.com/vercel/hyper/actions/runs/548818425#artifacts

**Comment by xoorath** [comment]
Thanks @LabhanshAgrawal

I'm still seeing it on 3.0.2 canary; are you saying it's fixed and will be in the next canary, or that it's fixed and I should see that it's fixed?

I want to stay on a release stream and not download from CI; I can test in the next canary version when it's out if you think the fix will be in there.

**Comment by LabhanshAgrawal** [comment]
@xoorath it should be there in the canary release https://github.com/vercel/hyper/releases/tag/v3.1.0-canary.4 (no windows build in it though)
I am saying that it's working in the canary branch atm
I don't when we'd be able to do a stable release though

**Comment by xoorath** [comment]
Okay @LabhanshAgrawal, I'll look for it the next time a canary release for windows includes the change.
