### ISSUE TITLE
Feature request: ctrl-f Find in Scrollback

### ISSUE THREAD

**Issue by cjb** [zeit/hyper#140]
Ideally with incremental search and fancy highlighting and all that jazz.

Thanks for writing hyperterm! <3

**Comment by chibicode** [comment]
I wonder if this can be done from a plugin somehow. One solution is to use `tmux`, but I've moved away from it...

**Comment by atdrago** [comment]
Agree, this is a much needed feature. Very helpful when looking through diffs, and would bring Hyperterm closer to feature parity with Terminal.

**Comment by emaillenin** [comment]
I am not able to get even the regular "Find" to work. Nothing happens with "Cmd + F".

**Comment by seanyesmunt** [comment]
Any update on this? Like @emaillenin `Cmd + F` doesn't work for me.

**Comment by dimitrieh** [comment]
Would love to have this, one of the most used features in iterm2

**Comment by bobber205** [comment]
Not having this makes this almost unusable for me.

**Comment by aleclarson** [comment]
This is the only reason I don't use hyper over the macOS terminal.

Any chance there will be work done on this soon? 😀

**Comment by saketmehta** [comment]
If this is done, bye bye iTerm. But for now, I'm gonna stick with iTerm.

**Comment by ephetic** [comment]
Gonna jump on the bandwagon here.  I tried hyper right after it came out, but switched back to iTerm after a couple weeks because of the lack of scrollback search.  Just tried it again for a week and I still can't live without it.  I could learn tmux, but then I probably could live without iTerm too.

**Comment by stephencookdev** [comment]
Also in the boat of "really want to use Hyper, but literally cannot use a terminal without Ctrl+F"

I've raised a PR https://github.com/zeit/hyper/pull/1793 to add a very basic incremental search feature. Would appreciate reviews :)

**Comment by jaanauati** [comment]
i just published this plugin, it implements  basic text search controls (input, buttons, menu 
 and shortcuts). Hope it helps u all:
http://npmjs.com/package/hyper-search

**Comment by seanyesmunt** [comment]
@jaanauati Awesome! I'll be sure to try it out!

**Comment by jcrben** [comment]
> I tried to work around this by selecting all text using Command+A and pasting it to a text editor to search, but Command+A doesn't seem to select text in scrollback.

@chibicode - Command+A seems to select text in the scrollback for me - using 2.0.0 - for those needing a workaround

**Comment by jackHedaya** [comment]
Any idea as to when this will get added to the stable build? Still not seeing this feature on v3.0.2 (macOS).

**Comment by Stanzilla** [comment]
This is now implemented in the canary CI builds, I don't do release so no idea when that will be stable.

**Comment by moritzWa** [comment]
Should this be working by now? 

I see this search bar appearing, but with no function/result:

<img width="413" alt="Screenshot 2021-08-11 at 11 00 14" src="https://user-images.githubusercontent.com/42035131/129079848-3a0cb33e-9bc4-4f77-a063-98d972052636.png">

**Comment by LabhanshAgrawal** [comment]
@moritzWa yeah, it should work now. Can you please open an issue if it's not working for you with the latest release.
