### ISSUE TITLE
Tiling is not working on Windows 10

### ISSUE THREAD

**Issue by mykytanikitenko** [zeit/hyper#1485]
- I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64 bit 
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mykytanikitenko/8153f3700c33200d00ac50fbe1225682
- **The issue is reproducible in vanilla Hyper.app**: Vanilla

## Issue

Windows 10 have tiling. When you are pulling window to left border it maximalizes to half of screen. To left top corner - a quarter of screen. It's not working with hyper window.

**Comment by stefanivic** [comment]
This issue is fixed with the : https://github.com/zeit/hyper/commit/0ff1cb9584df097159f23431fdf5feafb80a9cb9 Make sure you are running the latest version of Hyper.

**Comment by zodern** [comment]
The last release was 2 days before 0ff1cb9

**Comment by nealoke** [comment]
@stefanivic I'm not sure but I just downloaded hyper and installed it, still no tiling in windows 10 ?

**Comment by stefanivic** [comment]
@nealoke you can grab the release from AppVeyor including the latest commits : https://ci.appveyor.com/project/appveyor-zeit/hyper/build/1.0.506/artifacts These are *not official* releases.

**Comment by gutierri** [comment]
The problem persists in version> = 2.0.0. In my environment and positioning, but unlike Left on the Right and Right on the Left.
