### ISSUE TITLE
Cropped icon rendering with Powerline+Font Awesome font . 'Fix' with opening split panes.

### ISSUE THREAD

**Issue by paulklemm** [zeit/hyper#1769]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.4
- **Hyper.app version**: 1.3.1.1628
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/paulklemm/5ee36a36930a7ba0a895f2bcdc8c915d](https://gist.github.com/paulklemm/5ee36a36930a7ba0a895f2bcdc8c915d)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

I'm using ZSH with the [powerlevel9k](https://github.com/bhilburn/powerlevel9k) theme and [SourceCodePro+Powerline+Awesome Regular](https://github.com/gabrielelana/awesome-terminal-fonts/raw/patching-strategy/patched/SourceCodePro%2BPowerline%2BAwesome%2BRegular.ttf) font ([https://github.com/gabrielelana/awesome-terminal-fonts](https://github.com/gabrielelana/awesome-terminal-fonts)).

The icons are cropped in hyper.
![image](https://cloud.githubusercontent.com/assets/2169489/25499775/dce4bdf8-2b8c-11e7-9804-186e0f714564.png)

When I open a new split pane horizontally, the problem disappears, while the new pane is still rendered wrong.

![image](https://cloud.githubusercontent.com/assets/2169489/25499851/275083cc-2b8d-11e7-886e-f6c2a1546b2b.png)

Opening a third one doesn't help.

![image](https://cloud.githubusercontent.com/assets/2169489/25499874/369fb992-2b8d-11e7-8a8e-66daad0ebba9.png)

If you, however, split horizontally, you can also get the opposing pane fixed.

![image](https://cloud.githubusercontent.com/assets/2169489/25500007/ae0e0c36-2b8d-11e7-8de3-cabf4b478747.png)

**Comment by fsegouin** [comment]
Same issue here, noticed it on the previous version as well.

**Comment by fsegouin** [comment]
Any update on this?

**Comment by fsegouin** [comment]
If it helps: I am using `fish` with the ` oh-my-fish/theme-bobthefish` theme, as well as `MesloLGS Nerd Font` as hyper font.

**Comment by sjoeboo** [comment]
+1 also having the same 'icons cut off' issue. Using Zsh w/ InputMono Nerd Font.  Also seeing a split fixing it in the original window.

**Comment by mrmohtas** [comment]
I've now encountered this issue. ZSH, PowerLevel9K with FureCode Nerd Font

**Comment by paulklemm** [comment]
Update:

Related issues I could find:

- [https://github.com/zeit/hyper/issues/1336](https://github.com/zeit/hyper/issues/1336)
- [https://github.com/zeit/hyper/issues/1845](https://github.com/zeit/hyper/issues/1845)

It seems that PR [https://github.com/zeit/hyper/pull/1536](https://github.com/zeit/hyper/pull/1536) solves the problem. It was merged into master end of May and should therefore be in the next Hyper.js release.

🤞🏽

**Comment by paulklemm** [comment]
@deiga You're right. Just compiled the current codebase and the problem still persists.

**Comment by lucasqueiroz** [comment]
The interesting thing is that it only happens when there is a background color. 
With colored background:
![background](https://user-images.githubusercontent.com/29466590/28043934-c3980d8e-65aa-11e7-9368-e01a20fb1503.png)
With default color background:
![no-background](https://user-images.githubusercontent.com/29466590/28043935-c3985938-65aa-11e7-8ff4-798c58c5c66b.png)

**Comment by paulklemm** [comment]
@lucasqueiroz For me it's independent of the background color. Can you share your config?

**Comment by fsegouin** [comment]
@lucasqueiroz The bug you mentioning has something to do with your theme, nothing is cropped out.

**Comment by lucasqueiroz** [comment]
It's not the theme. I've removed the theme, added again. It only works when there is no background color for the text.

**Comment by mrmohtas** [comment]
Switched to iTerm as a result of this issue and it's working fine. Problem persists in Hyper with same config

**Comment by mrmohtas** [comment]
Any progress on this issue? This present in v1.4.3

**Comment by chhschou** [comment]
Seems like vscode terminal also has the same issue: https://github.com/Microsoft/vscode/issues/30289. Potentially issue upstream in xterm.js?

**Comment by paulklemm** [comment]
@chhschou is right, VS Code has the same problem: 

![screen shot 2017-09-14 at 08 56 34](https://user-images.githubusercontent.com/2169489/30415950-9692dedc-992a-11e7-85c8-939e0a09dda7.png)

**Comment by Tabrizian** [comment]
Any improvement on this issue?

**Comment by jobarbo** [comment]
mine works in vscode but have the same issue in Hyper

**Comment by lucasqueiroz** [comment]
For me, it has been fixed in 2.x

**Comment by jobarbo** [comment]
2.x ? isn't the last version 1.4.8?

**Comment by Tabrizian** [comment]
Check the prerelease section

On Sep 30, 2017, at 12:12 AM, jobarbo <notifications@github.com<mailto:notifications@github.com>> wrote:


2.x ? isn't the last version 1.4.8?

**Comment by chhschou** [comment]
On Hyper v2.0.3, still not fixed:
![image](https://user-images.githubusercontent.com/429067/31044190-0f60b664-a627-11e7-912b-10ce204b9c9f.png)

**Comment by chhschou** [comment]
I believe this is a simple fix, we should be using the `xterm-wide-char` to display the powerline characters css class instead of `xterm-normal-char`.

**Comment by fsegouin** [comment]
Seems to be fixed as of 2.0.4 (might be related to the recent fix in xterm.js).

**Comment by paulklemm** [comment]
@fsegouin It's partially fixed. I still experience problems as @chhschou describes. Some Icons are still cropped.

![screen shot 2017-10-23 at 12 25 36](https://user-images.githubusercontent.com/2169489/31884440-4c54c15a-b7ed-11e7-8acb-ebbc6f988ae9.png)

**Comment by gabrieldrs** [comment]
Hey, 2.0.4 didn't fix it for me, what did work for me though was adding this to .hyper.js config file:

```
termCSS: 'x-row .unicode-node {display:inline}',
```

**Comment by PabiGamito** [comment]
@gabrieldrs  Doing this seems to mess with the cursor, slightly offsetting it to the left when there are icons on the same line. Do you happen to know of any other fix for this?

**Comment by Stanzilla** [comment]
Hey there, to verify if this is indeed a Hyper issue or upstream at https://github.com/xtermjs/xterm.js/ could you please test if another xterm.js powered terminal shows the same problem you are experiencing? I suggest using https://github.com/Microsoft/vscode for testing. Thanks!

**Comment by PabiGamito** [comment]
@Stanzilla I was indeed experiencing the same issues in the vscode terminal. I have removed any icons to avoid this, so I haven't tested it since a bit after posting here.

**Comment by NearAutomata** [comment]
Special indicators (like the branch icon and less noticeable the git dot) are cropped in 2.1.0-canary.1:

![](https://i.imgur.com/Dcrwfvz.png)

Surprisingly this is bugged in VSCode as well.
