### ISSUE TITLE
Assertion failed when closing hyper after closing a tab on Windows

### ISSUE THREAD

**Issue by F21** [zeit/hyper#2143]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64-bit Creators Update (with latest updates)
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/F21/34fabe96045bf96e14b3717273a30d3c
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
To reproduce:
1. Start hyper.
2. Open a new tab (CTRL + SHIFT + T).
3. Close the tab.
4. Close hyper.
5. See error thrown by hyper:
![image](https://user-images.githubusercontent.com/2263040/29901523-b912d13c-8e3b-11e7-8cd0-d4f43288e02c.png)

**Comment by ksmigiel** [comment]
I also have this issue.

**OS version and name**: Windows 10 64-bit Creators Update (with latest updates)
**Hyper.app version**: 1.4.2
**Link of a Gist with the contents of your .hyper.js**: not changed
**Relevant information from devtools**: N/A
**The issue is reproducible in vanilla Hyper.app**: Is Vanilla

**Comment by pzi** [comment]
Experienced the same on Windows 8.1 Enterprise.

```
Hyper 1.4.2
Electron 1.6.12
win32 x64 6.3.9600
```

**Comment by Xemiru** [comment]
Pretty much the same issue, except I get it by simply using Close Session (from File menu or its keyboard shortcut) while only having one tab open.

Hyper 1.4.3 on Windows 7 Home Premium with [this config](https://gist.github.com/Xemiru/03604fcb85cab6d1b1dd94329642206b).

**Comment by matheuss** [comment]
cc @Tyriar

**Comment by bartleman** [comment]
Still having this issue on Hyper 1.4.3

**Comment by Tyriar** [comment]
@matheuss what version of node-pty is this using and how do you kill the process?

**Comment by matheuss** [comment]
cc @chabou can you check that please

**Comment by chabou** [comment]
We are using `node-pty@0.7.0`
And we kill it with `kill()` method: https://github.com/zeit/hyper/blob/1.4.3/app/session.js#L94

**Comment by chabou** [comment]
Oh...
I just found that we execute `kill()`on every sessions when user closes window. But there is a problem with session cleaning, because we are killing already killed session 😱 
That mean that we keep reference on every existed session...

**Comment by chabou** [comment]
This is a regression 😞 ... No overkill in v1.3.3

**Comment by chabou** [comment]
I fixed this session cleaning with #2176.

Can you try to reproduce this assertion on Windows with this `master` build please ?
https://ci.appveyor.com/api/buildjobs/hamc4rchyw3d08w8/artifacts/Hyper%20Setup%201.4.3.exe

**Comment by F21** [comment]
@chabou I installed the master build and the problem appears to be fixed! 👍

**Comment by chabou** [comment]
YES! 🎉  🎉  🎉 
Feel free to comment/reopened if this issue is not completely resolved!

**Comment by Tyriar** [comment]
Phew :wink:

**Comment by pzi** [comment]
Still happening for me on Windows 8 https://github.com/zeit/hyper/issues/2143#issuecomment-326240900

Using:
**Hyper 1.4.3 (stable)**

Plugins:
  - hyperterm-base-16-ocean (1.0.2)
  - hyperlinks (0.5.0)
  - hyper-blink (1.1.2)
  - hyperterm-cursor (0.0.3)
  - hyper-working-directory (1.0.1)

Had 4 tabs open and closed hyper using the "X" in the top right corner instead of shortcut or menu.

First error:

![image](https://user-images.githubusercontent.com/2037851/30095875-cc8f859a-9307-11e7-91cf-138e15a4fc3e.png)

Hit _ignore_ then got second error:

![image](https://user-images.githubusercontent.com/2037851/30095880-d6097b8a-9307-11e7-9b33-2193c540a7b9.png)

**Comment by chabou** [comment]
Are you using build that I linked in this issue or public stable? 🤔

**Comment by pzi** [comment]
Hey @chabou, public stable.

**Comment by F21** [comment]
@pzi Give this master a build a shot: https://ci.appveyor.com/api/buildjobs/hamc4rchyw3d08w8/artifacts/Hyper%20Setup%201.4.3.exe

**Comment by pzi** [comment]
Getting this when trying to install it from appveyor link:

![image](https://user-images.githubusercontent.com/2037851/30102536-8924b5ee-9322-11e7-9abc-f893f8b95e2a.png)

**Comment by F21** [comment]
@pzi, your problem seems very similar to these:
- https://github.com/zeit/hyper/issues/2046
- https://github.com/zeit/hyper/issues/2175

See if the proposed solutions in those issues work for you.

**Comment by pzi** [comment]
@F21 feels more like what went in f6bfbdf170a8414cbc6ca612c59579ceff14ace3 would solve it.

**Comment by chabou** [comment]
@pzi indeed what went in f6bfbdf solved your first issue.
Your issue with appveyor build is another different issue as @F21 said (thank you @F21 ).
