### ISSUE TITLE
Error updating plugins

### ISSUE THREAD

**Issue by silvenon** [zeit/hyper#312]
Each time I start HyperTerm or try to update plugins, I get this notification:

```
Error updating plugins
Check `~/.hyperterm_plugins/npm-debug.log` for more information.
```

My plugin works, but this error keeps coming up. Not sure how to start debugging because the said `npm-debug.log` doesn't exist. I tried reinstalling HyperTerm but still the same problem.

**Comment by jamesacampbell** [comment]
I have the same issue.

**Comment by jcurtis** [comment]
I have the same issue except my plugins don't work.

**Comment by jcurtis** [comment]
I was able to fix and update the plugins by doing `cd ~/.hyperterm-plugins && npm i` but I still get a failed to update plugins message on startup.

**Comment by silvenon** [comment]
Oh yeah, I forgot that it didn't work by itself, I had to do `npm i` same as you, @jcurtis.

**Comment by iamstarkov** [comment]
```plugin
# in your hyperterm-extension
npm link

# in ~/.hyperterm-plugins
npm link hyperterm-extension
```

then in `HyperTerm -> View -> Reload` to debug

**Comment by jamesacampbell** [comment]
My issue was solved by uninstalling node and installing again in homebrew. I had conflicts between versions and npm versions as well. All fixed.

**Comment by silvenon** [comment]
@iamstarkov I tried, but this isn't related to a specific plugin, but HyperTerm itself. I checked the console as well, but nothing.

**Comment by jcurtis** [comment]
Ah that makes perfect sense. I'm using nvm and had no system version of node running. Installing a version of node with homebrew looks to have fixed the problem. Not sure if this is something that can be fixed from the app perspective?

**Comment by alexciarlillo** [comment]
I am experiencing this with 1.0.0 on Windows. No npm-debug.log is created. I have node@7.2.1 and npm@3.10.10 installed via Chocolatey.

**Comment by austin-guevara** [comment]
Tried completely uninstalling node and reinstalling through brew, though I still get the "Error updating plugins" at every launch.

**Comment by Waquo** [comment]
I had this with hyper 1.0.0 on Windows. Problem was fixed after installing node (7.2.1) via chocolatey.

**Comment by jorge8168711** [comment]
This solve my problem on windows 10, i hope be useful.
http://superuser.com/questions/727316/error-in-command-line-the-system-cannot-find-the-path-specified

**Comment by novascreen** [comment]
I'm having the same issue on Windows 10 using coreybutler/nvm-windows to install Node.
Not seeing any error messages in the Dev console or OS notifications, it just doesn't install anything in `.hyper_plugins` so i have to run `npm i` there manually

**Comment by cdanyl** [comment]
Using bash `C:\\Program Files\\Git\\bin\\sh.exe` as default shell, cause the problem

**Comment by Alex0007** [comment]
I'm experiencing this problem on Linux. Node&npm installed with nvm and they are loaded using [bash-preexec](https://github.com/rcaloras/bash-preexec)

**Comment by asilvadesigns** [comment]
Currently experiencing this, really frustrating, tried reinstalling with node, homebrew several times, no luck.

**Comment by piratebroadcast** [comment]
I really want to try Hyper but it crashed instantly on startup after installing and remivbing a few normal plugins. Getting the same "Error updating plugins
Check `~/.hyperterm_plugins/npm-debug.log` for more information." error

**Comment by austinbutler** [comment]
Same issue on OS X with 1.2.0, tried reinstalling Brew-installed node, still happens even with no plugins. The log file referenced doesn't exist.

**Comment by rauchg** [comment]
I'm sorry this is happening! Can you provide some more information about:
- Node version and NPM version
- Location of `node` and `npm` in the `fs`
- Platform

when you encounter this bug?

**Comment by austinbutler** [comment]
1. Node v7.5.0
2. NPM 4.1.2
3. OS X 10.11.6

**Comment by srl295** [comment]
Mac, node v7.4.0. 
Seemed to fix it with:
```
cd ~/.hyper_plugins
nvm use 6
npm i
npm rebuild
#bang coconuts together
```

**Comment by TheJayWright** [comment]
I was able to generate npm-debug.log

This is the output I received.

`0 info it worked if it ends with ok
1 verbose cli [ '/Users/jwright/.nvm/versions/node/v6.9.5/bin/node',
1 verbose cli   '/Users/jwright/.nvm/versions/node/v6.9.5/bin/npm',
1 verbose cli   'link',
1 verbose cli   'hyperterm-extension' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData hyperterm-extension
8 silly fetchNamedPackageData hyperterm-extension
9 silly mapToRegistry name hyperterm-extension
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'hyperterm-extension',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'hyperterm-extension',
12 silly mapToRegistry   name: 'hyperterm-extension',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/hyperterm-extension
14 verbose request uri https://registry.npmjs.org/hyperterm-extension
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:47:47 PM
17 verbose request id 428d155521a29d3b
18 http request GET https://registry.npmjs.org/hyperterm-extension
19 http 404 https://registry.npmjs.org/hyperterm-extension
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 16 Feb 2017 20:47:47 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-atl6221-ATL',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1487278067.570100,VS0,VE339',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Thu, 16 Feb 2017 20:47:47 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-atl6221-ATL',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1487278067.570100,VS0,VE339',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/hyperterm-extension
22 silly fetchPackageMetaData     at makeError (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:969:12)
22 silly fetchPackageMetaData  error for hyperterm-extension { Error: Registry returned 404 for GET on https://registry.npmjs.org/hyperterm-extension
22 silly fetchPackageMetaData     at makeError (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
22 silly fetchPackageMetaData     at Request._callback (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
22 silly fetchPackageMetaData     at Request.self.callback (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:187:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:1048:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:969:12) pkgid: 'hyperterm-extension', statusCode: 404, code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/hyperterm-extension
27 verbose stack     at makeError (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
27 verbose stack     at Request._callback (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
27 verbose stack     at Request.self.callback (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:187:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at Request.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:1048:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:188:7)
27 verbose stack     at IncomingMessage.<anonymous> (/Users/jwright/.nvm/versions/node/v6.9.5/lib/node_modules/npm/node_modules/request/request.js:969:12)
28 verbose statusCode 404
29 verbose pkgid hyperterm-extension
30 verbose cwd /Users/jwright/.hyper_plugins
31 error Darwin 16.4.0
32 error argv "/Users/jwright/.nvm/versions/node/v6.9.5/bin/node" "/Users/jwright/.nvm/versions/node/v6.9.5/bin/npm" "link" "hyperterm-extension"
33 error node v6.9.5
34 error npm  v3.10.10
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/hyperterm-extension
37 error 404
38 error 404 'hyperterm-extension' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
`

**Comment by TheJayWright** [comment]
Also, I don't receive the message on load, but if I go to Plugins -> Update All Now, then I receive the error.

**Comment by fyears** [comment]
Meeting the same issue here. Fresh install hyper 1.2.1 downloaded from https://hyper-updates.now.sh/download/win on latest Windows 10, without node.js npm installed. Every time opening hyper or going to Plugins -> Update All Now I could receive this error.

**Comment by tylersticka** [comment]
Started happening to me as well, not sure if it started with 1.2.0 or 1.2.1. Referenced `npm-debug.log` doesn't exist. No nvm or anything installed.

1. Node 6.2.2
1. npm 3.9.5
1. macOS 10.12.3

**Comment by indexofrefraction** [comment]
same here, i had 1.2.1 freshly installed yesterday on macos 10.12.3.
worked fine until i tried to install a plugin.
installing plugin never worked, had the error on first try.
since then i get the error on each application start and when do "Plugins → Update All Now".
even getting rid of the error on start didnt work. (deleted all hyper related files)
it is annoying, plz give this a high priority!

Node 7.4.0, /usr/local/bin/node
npm 4.0.5, /usr/local/bin/npm
macOS 10.12.3

**Comment by greggh** [comment]
This is happening to me too. Load Hyper or go to the Plugins menu and Update All Now. I get the same error telling me to look at the debug log. The file doesnt exist.

macOS 10.12.3
Node 7.5.0
npm 4.1.2

Installed Node by downloading 7.5.0 from the main nodejs website via the dmg.

**Comment by fahadsiddiqui** [comment]
Same issue with me.
Node: 7.5.0
npm: 4.1.2
Hyper: 1.2.1

**Comment by winkerVSbecks** [comment]
Same issue here. I installed node using brew and manage versions using `n`. Also, have yarn installed through brew.

Node: `v7.4.0` `/usr/local/bin/node`
Npm: `4.1.2` `/usr/local/bin/npm`
Hyper: `1.2.1.1528`
on macOS 10.12.3

**Comment by crobinson42** [comment]
OSX Nvm using node 6.9.2 and npm 3.10 - I did a fresh install and tried adding a plugin and as soon as I saved the hyper.js file it threw the error about unable to update plugins and the npm debug log it says to review does not exist.

**Comment by freeall** [comment]
I downloaded the archive, extracted, moved to Applications folder, and then ran. Got the error immediately. So didn't have to install a plugin for it.

Does this work for anyone?

**Comment by cwattengard** [comment]
I had this problem using hyper 1.2.1 on w10 with node 6.9.3 and npm 4.2.0.

I fixed it by setting the "shell" property to "c:\\windows\\system32\\cmd.exe". By default on windows it's set to "", which works when starting hyper, but throws an error when trying to run npm (debugged that by starting hyper.exe from the command line)

**Comment by adrianoresende** [comment]
Same here
Node: v6.9.5 (installed from .dmg)
Npm: 3.10.10
Hyper: 1.2.1.1528
on macOS 10.12.1

**Comment by bitkomponist** [comment]
Node: v7.4.0 
Npm: 4.1.2
Hyper: 1.2.1.1528
on macOS 10.12.3

for me, changing the shell configuration from '' to '/bin/zsh' fixed the problem

**Comment by winkerVSbecks** [comment]
@bitkomponist where do I change that? I'm using oh my zsh. Wonder if that is the problem. Was  working previously.

**Comment by karlhorky** [comment]
> changing the shell configuration from '' to '/bin/zsh' fixed the problem

@bitkomponist Where did you change this configuration?

**Comment by freeall** [comment]
@winkerVSbecks in the config, `~/.hyper.js`
```
config: {
  ...
  shell: '/bin/zsh'
  ...
}
```

**Comment by freeall** [comment]
@bitkomponist It stopped complaining about the plugins, but now it's like it didn't load the `.bash_profile`

**Comment by bitkomponist** [comment]
@winkerVSbecks @karlhorky, @freeall is correct, you can also open the file by pressing cmd+, in the editor

**Comment by CodeMonkeyKevin** [comment]
@bitkomponist This working for me also. Used fish shell changing it to zsh restarting and switching it back to fish fixed this issue. i no longer get this error.

**Comment by bitkomponist** [comment]
@freeall .bash_profile is not used by zsh if i recall correctly, take a look at ~/.zshrc

**Comment by winkerVSbecks** [comment]
I can confirm that this works for me too.

**Comment by indexofrefraction** [comment]
it doesn't really make sense to set the shell to zsh if you want/need to use bash
bash is also the default shell for macos and from experience i don't change this for my working shell.
nonetheless it maybe helps to narrow down the problem!?

**Comment by karlhorky** [comment]
@bitkomponist @freeall this fixed it for me too, thanks!

**Comment by gsklee** [comment]
### Please stop reporting the recent v1.2.x related bug phenomenon inside this issue.

This issue (#312) is primarily about the circumstance where the absence of a system-wide `npm` command will lead to the update error. There is currently no concrete idea yet on how to fix this properly within Hyper.

While the symptom appears to be the same, it's unrelated with the recent v1.2.x breakage where the updating error message is showing up due to an already-identified configuration issue (#1513).

**Comment by wohlstadterm** [comment]
@bitkomponist @freeall worked for me as well!

**Comment by Zx-EvM** [comment]
I use Windows 10 Build 14393.693 and Hyper 1.2.1 and `shell: 'C:\\Windows\\System32\\cmd.exe',` in `.hyper.js` config file fix startup error http://imgur.com/a/e1cid `Error updating plugins`

**Comment by cedric-marcone** [comment]
Confirmed :
`config: {
  shell: '/bin/bash'
}`

=> Issue fixed.

**Comment by e-schultz** [comment]
I'm using fish, 

```
config:   {shell: '/usr/local/bin/fish' }
```

fixed ... thanks for the suggestions

**Comment by grigala** [comment]
@cedric-marcone worked like a charm. I'm using `zsh` 👍 

But I couldn't even find that `~.hyper_plugins/npm-debug.log` file in mentioned directory. Eeeh?
![img](http://i.imgur.com/eIdDZoD.png)

**Comment by iamstarkov** [comment]
@grigala its `~/.hyper_plugins/npm-debug.log` not sure if you have a typo or not

**Comment by iovis9** [comment]
@iamstarkov I couldn't find it either and there was no typo.

**Comment by iamstarkov** [comment]
@iovis9 i would say it was typo
![screen shot 2017-02-24 at 15 33 57](https://cloud.githubusercontent.com/assets/559321/23307131/b12c587c-faa6-11e6-8b51-1a2ad74d9044.png)

**Comment by iamstarkov** [comment]
@iovis9 how do you search for `~/.hyper_plugins` folder?

**Comment by phareim** [comment]
Windows 10-user here.

The problem dissapeared when I added a specific reference to the cmd in the `.hyper.js`-file.
i.e.:
`shell: ''` -> `shell: 'C:\\Windows\\System32\\cmd.exe'` fixed the issue.

**Comment by iamstarkov** [comment]
ok, got the same thing. plugins cant be updated and there is no `~/.hyper_plugins/npm-debug.log`
![screen shot 2017-02-27 at 10 21 16](https://cloud.githubusercontent.com/assets/559321/23355555/8c8c0850-fcd6-11e6-8337-e98258518ed8.png)
![screen shot 2017-02-27 at 10 21 25](https://cloud.githubusercontent.com/assets/559321/23355554/8c8b2c46-fcd6-11e6-82e6-e42f11bcd17f.png)

P.S. Sorry, @iovis9

**Comment by phareim** [comment]
Yeah, no npm-debug.log for me either.

**Comment by astrosquid** [comment]
@freeall That fixed it for me! Thanks.

Agree with the others though, there's no file at `~/.hyper_plugins/npm-debug.log`

macOS 10.12.3
Hyper version 1.2.1.1527

**Comment by 616b2f** [comment]
@freeall this also worked for me. Thank you so much!

Mac OS X 10.12.3
Hyper version 1.2.1.1528

**Comment by alejandrofloresm** [comment]
The solution provided by @freeall worked for me also 👍

**Comment by dipaktelangre** [comment]
I am having the same issue on widows. 
Which shell should I mentioned for windows as @freeall  suggested

**Comment by dipaktelangre** [comment]
I even tried to install packages form ```.hyper_plugins```  folder, was getting the issue for ```npm install``` too. 
![capture](https://cloud.githubusercontent.com/assets/2802393/23648232/c7d2b0d4-033f-11e7-8185-330e570b7ef0.PNG)

**Comment by jonbaer** [comment]
When running hyper it was dropping npm-debug.log to my $HOME dir, after copying ~/.hyper_plugins/package.json (and node_modules) to both $HOME *and* ~/.hyper_plugins everything works which leads me to believe the config paths may not be correct.

In source I see this:
app/plugins.js:const path = resolve(config.getConfigDir(), '.hyper_plugins');

If getConfigDir() resolves to $HOME by default shouldn't that be:
app/plugins.js:const path = resolve(config.getConfigDir() + '.hyper_plugins');

(since you are dealing with a directory) <guess>

**Comment by ppot** [comment]
@jonbaer The resolve joint the 2 parts. So `config.getConfigDir()` and `'.hyper_plugins` will be concat.

resulting in '~/.hyper_plugins' if you are on linux/macOS. On windows I believe it will be you're user path?

**Comment by rinchen** [comment]
I get the same error with details of


>joey@Josephs-iMac-2:~$
>/Applications/Hyper.app/Contents/MacOS/Hyper 
>running in prod mode
>electron will open file:///Applications/Hyper.app/Contents/Resources/app/index.html
>Checking for notification messages
>No matching notification messages
>TypeError: Cannot read property 'match' of undefined
>    at shellEnv.then.env (/Applications/Hyper.app/Contents/Resources/app/plugins.js:244:29)
>[Notification] Error updating plugins.: Check `~/.hyper_plugins/npm-debug.log` for more information.

**Comment by Zx-EvM** [comment]
# Note for Windows 10:

If you need to update or install new plugins you need to use `shell: 'C:\\Windows\\System32\\cmd.exe'`. And after you install new plugins you can use `shell: 'C:\\Windows\\System32\\bash.exe'`. I think this happens because hyper terminal installed on Windows and Windows Subsystem for Linux work like Linux PC and can not "know" path to hyper plugins directory.

Also note that WSL to access to `C:/` uses `/mnt/c/`

**Comment by dipaktelangre** [comment]
@Zx-EvM  I am really happy to heard that it works on windows as I am too excited about this terminal. 
Can you please explain the step, What configuration need to do after installation hyper for the installation of plugins.

**Comment by dipaktelangre** [comment]
@Zx-EvM  I tried by setting ```shell: "C:\\Windows\\System32\\bash.exe"``` or ```shell: 'C:\\Windows\\System32\\cmd.exe'``` nothing is working

**Comment by Zx-EvM** [comment]
@dipaktelangre okay. Now, suppose that you are need to install new plugin, for example [hyper-material-theme](https://github.com/equinusocio/hyper-material-theme) (it's not ads). For that, first you need to change your shell configuration to `shell: 'C:\\Windows\\System32\\cmd.exe'` (if now using bash) and install all you want.

Next, after installation is complete you can again use WSL by `shell: 'C:\\Windows\\System32\\bash.exe'`

**Comment by rinchen** [comment]
The 1.3.0 release, plus an npm update, fixed this for me on Mac OS.

**Comment by iamstarkov** [comment]
fixed for me on os x as well

**Comment by dipaktelangre** [comment]
@Zx-EvM  I Updated to the 1.3.0 and set ```shell: 'C:\\Windows\\System32\\cmd.exe'``` . 
It works. Thanks a lot

**Comment by Zx-EvM** [comment]
@dipaktelangre how are you upgrade hyper.is on Windows? You just reinstall it?

**Comment by aurenen** [comment]
@Zx-EvM I have the same problem, but switching to cmd for shell doesn't remove the error that pops up every time I load hyper.app 1.3.1

**Comment by brabidou** [comment]
@aurenen I didn't have node/npm installed on the path. Try installing/reinstalling node and you can verify node/npm are installed correctly by doing `node -v` and `npm -v`.

**Comment by aurenen** [comment]
@brabidou I've already verified that they're installed, and reinstalling doesn't change anything. I think at this rate I might just give up using any plugins. :(

**Comment by chabou** [comment]
@aurenen 
> I have the same problem
Due to fact that, 2-3 various problems has been mixed here, it is difficult to understand it.
What is your problem exactly? What error did you get?

Workaround for main problem reported here, is to set shell in config file: https://github.com/zeit/hyper/issues/312#issuecomment-281407215

**Comment by jakubsvobodacz** [comment]
Hi, I had the same issue with the latest Hyper on Windows 10 with the latest update. i did not have nodejs installed, so once I did that, ran Hyper, I got the message again but I went to Plugins > Update All Now and it showed that plugins are updated, then I restarted Hyper. The message was gone from then.

**Comment by lietu** [comment]
What I've done to "fix" the issue on Windows 10 is:

 - Trigger the notification via the menu `Plugins -> Update All Now`
 - Open the Action Centre from the bottom right of the screen
 - Right click on the error notification and choose `Turn off notifications for this group`

I don't think there's a lot of useful notifications using that system anyways, so I generally just block most annoying notifications like that.

**Comment by bartleman** [comment]
On Windows 10, hyper 1.3.3 I installed node for windows from their main site and then it worked fine.

**Comment by tuxracer** [comment]
It seems to have an undocumented dependency on systemwide node being available

**Comment by chabou** [comment]
We are working on it [here](https://github.com/zeit/hyper/pull/1897) and [here](https://github.com/zeit/hyper/pull/381)

**Comment by vai21** [comment]
Just download node.js package from here https://nodejs.org/en/ and install it to your windows 10. I assume you using windows 10 because I have this issue before after installing node.js the update works.

**Comment by nagman** [comment]
I tried almost every solutions so far, but what actually solved the problem was that I had only one instance of node.js running on WSL.

I totally could use node and npm with bash or zsh.

But as the Hyper User folder is located in the Windows filesystem (and I hadn't installed node.js on Windows), the plugins couldn't be updated.

So I just fixed it by installing node.js on Windows too. And it worked!

**Comment by chabou** [comment]
@nagman can you try with master? #381 has been merged. No more external `node` and `npm` dependency! 🎉

**Comment by svincent** [comment]
@chabou I was running into this issue with Hyper 1.3.3 which I got off of https://hyper.is. How would one go about testing the `master` branch without having Node globally installed in Windows?

**Comment by chabou** [comment]
You can use Appveyor build of each commit in master.
Last build is currently: https://ci.appveyor.com/api/buildjobs/8ko2jh7rxpbr99wb/artifacts/Hyper%20Setup%201.3.3.exe

Please confirm me that everything is ok with this build.

**Comment by cfjedimaster** [comment]
I'm running into this now too - started maybe a week ago. Using WSL, version 1.4.3. Running npm i in my .hyper_plugins in Windows CMD did not help. Node+npm work generally just fine in both WSL and cmd.exe.

**Comment by cfjedimaster** [comment]
Ok, for me, it was a bad plugin. I never saw a npm log written though so I couldn't tell what was wrong until I deleted my node_modules and then did a `npm i`. Then the error showed up right away.

**Comment by chabou** [comment]
Since 1.4.0, Hyper do not depend on system node+npm anymore.
It should just work.

@cfjedimaster what is your error?

**Comment by cfjedimaster** [comment]
@chabou for me - it was the plugin saying it didn't support Windows. Not sure why it didn't matter before.

**Comment by chabou** [comment]
@cfjedimaster Whet is this plugin?

**Comment by cfjedimaster** [comment]
@chabou honestly don't remember - I think it was something status something.

**Comment by chabou** [comment]
Considering this issue fixed.
Please add a comment if I missed something

**Comment by JacobDB** [comment]
I'm still periodically having this problem, but I'm not 100% sure if it's the same issue. For some reason when updating plugins, I often get an error:

`Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Jacob\.hyper_plugins\node_modules\electron\dist\resources'`

If I go and delete that folder myself, everything works just fine. It's like there's something running out of order or something.

**Comment by manastalukdar** [comment]
I have the exact same problem as @JacobDB .

```
Error: ENOTEMPTY: directory not empty, rmdir
'C:\Users\user\.hyper_plugins\node_modules\electron\dist\resources'
```

Manually deleting this folder for now to get past the plugin update error.

OS: Microsoft Windows [Version 10.0.16299.309]
Hyper: 1.4.8.
nodejs: 9.8.0
npm: 5.7.1.
