### ISSUE TITLE
Getting the error "execvp(3) failed: No such file or directory" when opening hyper on Ubuntu 18.04

### ISSUE THREAD

**Issue by joybhallaa** [zeit/hyper#3703]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04 with the latest updates
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joybhallaa/323f67b019209fb550713b0c336a5b99 

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I have downloaded hyper version **3.0.2** on my Ubuntu 18.04, there were no problems in the download part.
When I opened the hyper app, I got greeted with the error **execvp(3) failed: No such file or directory**.

Things that I've tried: 
1. Go to **view->reload** & **view-reload**

**Comment by anthonykrivonos** [comment]
I was having the same issue and this is how I fixed it: navigate to the `Hyper` preferences (it's a file called `.hyper.js` and change the `updateChannel` to `'canary'`. Then, simply reload the terminal and let Hyper update itself. Let me know if that fixes things.

**Comment by joybhallaa** [comment]
Hey @anthonykrivonos, I tried your solution, but it did not work for me, but I looked around and found out that the *execvp(3)* error occurs when there is a issue with the path or terminal. So I looked into the *hyper.js* file and found out that the default shell that should be run was not there, so I added */bin/bash* and it worked, I'm going to attach a link to the gist which may help other people.
Should I open a new issue to add a default path ? 

[Gist](https://gist.github.com/joybhallaa/9610dd2059539df83725befd3be34dd4)

**Comment by amirrezasalimi** [comment]
@joybhallaa  thanks you,  its worked

**Comment by typemismatch** [comment]
This is still an issue, just installed today on OSX 10.14.6 and Hyper 3.0.2 and there was no shell in the .js file.

**Comment by jcklpe** [comment]
I'm having this problem too. https://spectrum.chat/zeit/hyper/execvp-3-failed-no-such-file-or-directory-best-settings-for-multi-os~e81ac056-238e-4322-ac3c-1bc51a785892

**Comment by matanglahav** [comment]
@joybhallaa  Thank you, Worked like a charm!

**Comment by joehanko** [comment]
@joybhallaa worked for me too, thanks!

**Comment by joybhallaa** [comment]
Welcome, everyone! Is this issue still there? I'd like to open an issue to work on this.

**Comment by BLZH93** [comment]
Yup! still going on! Used your code and it fixed it in a whiff. Thank you bud!

**Comment by Shellchuck** [comment]
@joybh98 Hi, could you please share your code one more time? The gist is unavailable.

**Comment by joybh98** [comment]
@Shellchuck https://gist.github.com/joybh98/9610dd2059539df83725befd3be34dd4
here you go !

**Comment by Shellchuck** [comment]
@joybh98 Thank you!

**Comment by ji-ggy** [comment]
@joybh98 where can i find hyper.js file?
 i open my hyper terminal and click preferences but hyper.js not show up.

**Comment by joybh98** [comment]
if you're using linux, it should be in your home directory.
Type `ls -alF` or `ll` if you're on ubuntu or ubuntu based distros

**Comment by rafaelstz** [comment]
To me, it worked when I changed the **shell** to this path below in the `~/.hyper.js`.

```
...
 shell: '/bin/zsh',
...
```

**Comment by parichaypari1986** [comment]
I don't have updateChannel in that hyper.js file. How do I solve the same problem

**Comment by Bekhzod2022** [comment]
that worked for me too. Thanks
