### ISSUE TITLE
Entering a "~" / "`" symbol does not work with German keyboard

### ISSUE THREAD

**Issue by swernerx** [zeit/hyper#579]
I have a iMac with a German keyboard. Entering the tilde symbol using the normal key shortcut `alt+n` does not work. The same with the backtick symbol "`" itself which is placed after the`ß` symbol.

There is also some issue with the dollar sign (shift+3). This jumps a word to the beginning instead of entering the symbol.
## 

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 15.6.0

**Comment by MrRio** [comment]
Hi there, Could you try the master version? If you follow the contribute instructions in the README, that should get you going.

**Comment by dj-hedgehog** [comment]
@MrRio I have the same problem and just tried it. We still can not enter ~

**Comment by MrRio** [comment]
Can you do

```bash
git fetch
git checkout debug-keyboards
```

Then View -> Toggle Developer Tools.

If you could press each of those keys and paste me the output

**Comment by MrRio** [comment]
oh, and npm run dev && npm start

**Comment by dj-hedgehog** [comment]
This is the output:

```
{
altKey : true,
code : "KeyN",
key : "Dead",
metaKey: false,
shiftKey : false
}
```

**Comment by MrRio** [comment]
Try this branch https://github.com/zeit/hyperterm/pull/584

**Comment by MrRio** [comment]
The fix-international-tilde branch should sort the tilde issue, the others I need output for, and if they're not the same across all keyboards we may either have to ask the OS for the keyboard layout, or wait for https://github.com/zeit/hyperterm/pull/214 to land

**Comment by dj-hedgehog** [comment]
Awesome, #584 works:

![image](https://cloud.githubusercontent.com/assets/7140800/17457398/50526e68-5bf7-11e6-8b04-532be4cf847b.png)

**Comment by alrek-consulting** [comment]
I am just buzzing in to say that I experience the same issue on a Norwegian keyboard layout (MacBook Pro 2012)

**Comment by dj-hedgehog** [comment]
@alrek-consulting Have you tested #584 ?

**Comment by onbjerg** [comment]
Same with Danish keyboards as well.

**Comment by dj-hedgehog** [comment]
C'mon people. This repo feels almost like Facebook or the YouTube comment section.

@onbjerg & @thomas-alrek Plese checkout #584 and say whether it fixes the tilde for you. If that or reading the few comments in this issue too much work for you better don't say anything at all.

**Comment by onbjerg** [comment]
@dj-hedgehog Relax. I tried and I had the same issue as you. No need to be rude, at all.

I was merely pointing out that it was ALSO an issue for Danish keyboards (even on #584), which I think could aid in debugging, but I don't know. It has also been a long-standing issue in Atom.

**Comment by dj-hedgehog** [comment]
We're well aware that this is an issue with Danish (#213), Swedish, Norwegian etc. keyboards.

Can you try 

```
git fetch
git checkout debug-keyboards
```

and give us the output of the non-working keys?

**Comment by MrRio** [comment]
It's a lovely sunny Monday over here in the UK. Let's keep it nice. 😀🌞

**Comment by dj-hedgehog** [comment]
In Germany its cloudy with no chance of ´, ` working :disappointed_relieved:

**Comment by wcastand** [comment]
Hi, i'm on a mac with a french keyboard: 

<img width="271" alt="capture d ecran 2016-08-22 a 11 44 18" src="https://cloud.githubusercontent.com/assets/2178244/17850520/d5bbe788-685d-11e6-9bc0-088e381bdc37.png"><img width="321" alt="capture d ecran 2016-08-22 a 11 46 04" src="https://cloud.githubusercontent.com/assets/2178244/17850562/0ba793c4-685e-11e6-8ce7-2dccdf92dfe2.png">


I tried to ```git checkout debug-keyboards``` and i still can't use "~" or "`"

**Comment by dj-hedgehog** [comment]
@wcastand The branch `debug-keyboards` only shows the keys you pressed in the console. Feel free to post these for the not-working combinations here!

**Comment by wcastand** [comment]
Hey, sorry my bad :/
this is the result of the console log  for "~" : 

```KeyboardEvent {isTrusted: true, key: "Dead", code: "KeyN", location: 0, ctrlKey: false…}```

And for "`":

```KeyboardEvent {isTrusted: true, key: "Dead", code: "Backslash", location: 0, ctrlKey: false…}```

If you need all the object, let me know :)

**Comment by Jonas-Drotleff** [comment]
It seems like this issue was fixed with the release of 0.8.1.

**Comment by bellstrand** [comment]
Still not working in 0.8.3 with a Swedish keyboard (mac).
```javascript
{
    isTrusted: true,
    key: "Dead",
    code: "BracketRight",
    location: 0,
    keyCode: 221,
    keyIdentifier: "Unidentified"
} ... and more
```

**Comment by pcalves** [comment]
This issue could probably be closed in favor of #29. Everyone interested in this should also subscribe to #214 which looks to provide a fix for this! 🙌

**Comment by AndersonFirmino** [comment]
I have the last version 0.8.3 and this bug remains im my Linux Mint :cry:
